from pathlib import Path
import sys, shutil
sys.path.insert(0, str(Path('tmp/pdfs/review-deps').resolve()))
import fitz
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.colors import HexColor
from pypdf import PdfReader, PdfWriter

root=Path.cwd()
src=root/'output/pdf/walton-county-fy2027-budget-book-gfoa-ready.pdf'
work=root/'tmp/pdfs/review'
work.mkdir(exist_ok=True)
backup=work/'budget-before-checklist.pdf'
if not backup.exists(): shutil.copy2(src,backup)
doc=fitz.open(backup)
# Render an overview of every original page for review.
from PIL import Image, ImageDraw
for start in range(0,len(doc),24):
    sheet=Image.new('RGB',(1200,6*280),'#dddddd'); d=ImageDraw.Draw(sheet)
    for j in range(start,min(start+24,len(doc))):
        p=doc[j].get_pixmap(matrix=fitz.Matrix(.36,.36),alpha=False)
        im=Image.frombytes('RGB',[p.width,p.height],p.samples); im.thumbnail((290,255))
        x=(j-start)%4*300; y=(j-start)//4*280
        sheet.paste(im,(x,y+20)); d.text((x+5,y+3),str(j+1),fill='black')
    sheet.save(work/f'contact-{start+1}.png')

# Each row maps a primary question; notes identify secondary-detail improvements.
cols=[[
('Community priorities | criteria p. 8',None),
('Organizational challenges','A  12-14, 27'),('Community challenges','A  12-14'),('Budget response to challenges','A  13, 27-31'),('Results expected this budget year','A  27, 57-91'),
('Value | criteria p. 9',None),('Public benefits and services','A  15, 26-31'),('Cost to government / public','P  4, 15, 26, 28 [1]'),
('Long-term outlook | criteria p. 10',None),('Future effect of current decisions','P  36, 110-111 [2]'),('Effect on reserves','P  23, 36, 106-111 [2]'),('Expenses deferred to future years','P  36, 38-39 [3]'),('New ongoing spending obligations','P  35-36, 38 [3]'),('Historical trends / future outlook','P  96, 106, 110-111 [2]'),
('Revenue | criteria p. 11',None),('Anticipated revenue','P  15, 32, 93-98 [1]'),('Diversity of revenue sources','A  32, 95-98'),('Control over rates and revenue','P  32, 95 [4]'),('Restrictions on revenue uses','P  32, 95, 116-123 [4]'),('Who bears the revenue burden','A  18-19, 32, 95')
],[
('Personnel | criteria p. 12',None),('Total budgeted staff','P  4, 34, 101 [5]'),('Personnel cost change','A  34-35, 101'),('Staffing increases / reductions','P  34, 101 [5]'),('Drivers of personnel costs','P  34-35 [5]'),
('Departments | criteria p. 13',None),('Services for each department','A  42-48, 57-91'),('Costs for each department','P  54, 56-91, 99-100 [1]'),('Accountability for results','A  27, 57-91'),
('Programs / services | criteria p. 14',None),('Major programs identified','A  28-31'),('Cost of each major program','P  28, 93-100 [1]'),('Program service-level goals','A  29-31, 57-91'),('Alignment with priorities','A  12-13, 27-31'),('Revenue generated by programs','P  29, 57-91 [6]'),
('Capital | criteria p. 15',None),('Definition of capital spending','A  37, 113, 116'),('Level of capital spending','P  37, 39, 114-123 [1]'),('Project prioritization','A  38-39, 114-115'),('Capital funding sources','A  38, 113, 116-123'),('New / replacement / rehabilitation','P  38-39, 116-123 [3]'),('Major projects and delivery detail','P  38, 115-123 [3]')
],[
('Budget process | criteria p. 16',None),('How budget is developed','A  20-23'),('Who prepares the budget','A  20-21'),('How priorities are considered','A  12-13, 20, 40'),('When decisions occur','A  20-21, 40'),('When public can participate','A  20-21, 40'),
('Budget document | criteria p. 17',None),('Access from government website','V  Website evidence needed'),('Organization / contents','A  5-6; PDF bookmarks'),('Prominent budget message','A  3-4, 15'),('Effective graphics and images','A  7-8, 15, 26-40'),('Accessibility compliance','P  PDF structure [7]'),
('Budget in brief | criteria p. 18',None),('Concise overview','P  15 [1]'),('Relevant budget content','A  15'),('Distribution to residents','V  Distribution evidence needed'),('Attractive design','A  15'),
('Other formats | criteria pp. 19-20',None),('Website: access; interactivity;','V  Separate website review'),('accessibility; timely updates','V  Separate website review'),('Video: message; education;','V  Linked videos not reviewed'),('local relevance; audience / promotion','V  Linked videos not reviewed'),('Other media: tools; effectiveness','V  Campaign evidence needed')
]]
c=canvas.Canvas(str(work/'checklist.pdf'),pagesize=(792,612))
c.setFillColor(HexColor('#004029')); c.rect(0,531,792,81,fill=1,stroke=0)
c.setFillColor(HexColor('#e8c95e')); c.setFont('Helvetica-Bold',9); c.drawString(24,589,'INTERNAL REVIEW ONLY  |  REMOVE LAST PAGE BEFORE PUBLICATION')
c.setFillColor(HexColor('#ffffff')); c.setFont('Helvetica-Bold',19); c.drawString(24,565,'GFOA Budget Review Checklist')
c.setFont('Helvetica',9); c.drawString(24,547,'FY2027 Walton County  |  Attached criteria dated 8/1/2025  |  Review: September 8, 2026')
c.setFillColor(HexColor('#263b31')); c.setFont('Helvetica',8.5)
c.drawString(24,516,'A = addressed   P = partial / correction needed   V = not verified in PDF. References are PDF page numbers (1-133).')
c.drawString(24,503,'All primary questions are mapped below; bracketed numbers refer to gap notes. A is not an official GFOA score.')
sty=ParagraphStyle('r',fontName='Helvetica',fontSize=8,leading=8.5,textColor=HexColor('#243a30'))
for k,rows in enumerate(cols):
    x=24+k*250; y=487
    for title,ref in rows:
        if ref is None:
            c.setFillColor(HexColor('#e8eee9')); c.rect(x,y-14,242,15,fill=1,stroke=0)
            c.setFillColor(HexColor('#004029')); c.setFont('Helvetica-Bold',8.7); c.drawString(x+4,y-10,title); y-=17
        else:
            p=Paragraph(title,sty); w,h=p.wrap(228,30)
            c.setStrokeColor(HexColor('#809487')); c.rect(x+1,y-7,5,5,stroke=1,fill=0)
            p.drawOn(c,x+11,y-h+2); y-=h
            c.setFont('Helvetica-Bold',7.8); c.setFillColor(HexColor('#735323') if ref.startswith('P') else HexColor('#4a6254')); c.drawString(x+11,y-7,ref); y-=9
    print('column bottom',k,y)
c.setFillColor(HexColor('#ffffff')); c.rect(0,0,792,80,fill=1,stroke=0)
notes='[1] Reconcile financial totals / scopes. [2] Reconcile forecasts; show reserve classifications and policy target. [3] Identify deferred needs, full project funding, schedules, asset type and annual operating costs. [4] Resolve conflicting revenue restrictions / control labels. [5] Reconcile staffing scopes and personnel percentages. [6] Map revenue and subsidy to each major program. [7] Content-level accessibility tags are missing; remediation and validation needed.'
p=Paragraph(notes,ParagraphStyle('n',fontName='Helvetica',fontSize=8,leading=10)); _,h=p.wrap(744,70); p.drawOn(c,24,69-h)
c.setFont('Helvetica',7.5); c.setFillColor(HexColor('#41594a')); c.drawString(24,14,'Optional media are not mandatory missing items. See gfoa-budget-review.md for detailed findings. Remove PDF page 134 to detach.')
c.showPage(); c.save()
w=PdfWriter(); w.clone_document_from_reader(PdfReader(backup)); w.add_page(PdfReader(work/'checklist.pdf').pages[0]); w.add_outline_item('Internal GFOA review checklist - removable',133)
with src.open('wb') as f: w.write(f)
out=fitz.open(src); out[-1].get_pixmap(matrix=fitz.Matrix(1.8,1.8),alpha=False).save(work/'checklist.png')
assert len(out)==134
assert all(out[i].get_text()==doc[i].get_text() for i in range(133))
print('Verified original 133 page texts unchanged; checklist is page 134.')
